export const ETF_DATA = [
  {
    etf_symbol: "IBIT",
    etf_name: "iShares Bitcoin Trust",
    crypto_name: "Bitcoin",
    crypto_symbol: "BTC",
    company_name: "Blackrock",
  },
  {
    etf_symbol: "FBTC",
    etf_name: "Fidelity Wise Origin Bitcoin Fund",
    crypto_name: "Bitcoin",
    crypto_symbol: "BTC",
    company_name: "Fidelity",
  },
  {
    etf_symbol: "BITB",
    etf_name: "Bitwise Bitcoin ETF",
    crypto_name: "Bitcoin",
    crypto_symbol: "BTC",
    company_name: "Bitwise",
  },
  {
    etf_symbol: "ARKB",
    etf_name: "ARK 21Shares Bitcoin ETF",
    crypto_name: "Bitcoin",
    crypto_symbol: "BTC",
    company_name: "Ark",
  },
  {
    etf_symbol: "BTCO",
    etf_name: "Invesco Galaxy Bitcoin ETF",
    crypto_name: "Bitcoin",
    crypto_symbol: "BTC",
    company_name: "Invesco",
  },
  {
    etf_symbol: "EZBC",
    etf_name: "Franklin Bitcoin ETF",
    crypto_name: "Bitcoin",
    crypto_symbol: "BTC",
    company_name: "Franklin",
  },
  {
    etf_symbol: "BRRR",
    etf_name: "Valkyrie Bitcoin Fund",
    crypto_name: "Bitcoin",
    crypto_symbol: "BTC",
    company_name: "Valkyrie",
  },
  {
    etf_symbol: "HODL",
    etf_name: "VanEck Bitcoin Trust",
    crypto_name: "Bitcoin",
    crypto_symbol: "BTC",
    company_name: "VanEck",
  },
  {
    etf_symbol: "BTCW",
    etf_name: "WisdomTree Bitcoin Fund",
    crypto_name: "Bitcoin",
    crypto_symbol: "BTC",
    company_name: "WTree",
  },
  {
    etf_symbol: "GBTC",
    etf_name: "Grayscale Bitcoin Trust",
    crypto_name: "Bitcoin",
    crypto_symbol: "BTC",
    company_name: "Grayscale",
  },
  {
    etf_symbol: "BTC",
    etf_name: "Grayscale Bitcoin Trust (BTC)",
    crypto_name: "Bitcoin",
    crypto_symbol: "BTC",
    company_name: "Grayscale",
  },
];
