name: Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    # ambil code dari repo
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # setup node di GH Action runner
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    # install dep di GH Action runner
    - name: Install dependencies & Build
      run: |
        npm install
        npm run build

    # Setup SSH Key di GH action agar bisa menggunakan rsync
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    # Masuk ke dalam EC2, bikin folder crypto-tracker
    - name: Create Project Folder on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p ~/crypto-tracker

    - name: Deploy Code to EC2
      run: |
        rsync -avz --delete --exclude=node_modules --exclude=.git -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
          .next/ package.json package-lock.json public/ src/ \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/crypto-tracker/

    - name: Deploy .env to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "${{ secrets.ENV_FILE }}" > ~/crypto-tracker/.env

    - name: Install Dependencies & Restart PM2 in EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/crypto-tracker
          npm ci --omit=dev
          
          # Cek apakah aplikasi sudah berjalan, jika tidak, start
          if pm2 describe crypto-tracker > /dev/null; then
            pm2 restart crypto-tracker
          else
            pm2 start npm --name "crypto-tracker" -- run start
          fi

          pm2 save  # Pastikan aplikasi tetap berjalan setelah reboot
