name: Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/crypto-tracker
          git pull origin master
          npm install
          npm run build
          pm2 describe crypto-tracker > /dev/null || pm2 start npm --name "crypto-tracker" -- run start
          pm2 restart crypto-tracker
    